"use client";

import * as React from "react";
import { Wand2, Loader2, AlertTriangle } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Checkbox } from "@/components/ui/checkbox";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { convertRK9ToFormData, type RK9TeamData } from "@/lib/rk9-import";
import { applyNameOverride, normalizePlayerName } from "@/lib/player-name-overrides";
import { buildPlacementColumnWrappers } from "@/lib/column-wrapper-defaults";
import { getFlagsForPlayer } from "@/lib/player-flag-config";
import { createDefaultTournamentData } from "@/lib/tournament-defaults";
import type { StandingEntry, StandingsMode } from "@/lib/challonge";
import type { Pokemon, PlayerCount, TournamentData } from "@/lib/types";

// Sizes the graphic can render
const SUPPORTED_SIZES: PlayerCount[] = [4, 8, 16, 32, 64];

interface RosterPlayer {
  firstName: string;
  lastName: string;
  screenName: string;
  country: string;
  teamListUrl?: string;
}

interface ChallongeTournamentMeta {
  name: string;
  state: string;
  startedAt: string | null;
  completedAt: string | null;
}

/** One row of the review table: a standings entry and the roster row it matched */
interface ReviewRow {
  entry: StandingEntry;
  rosterIndex: number | null;
  autoMatched: boolean;
}

type Step = "input" | "review" | "importing";

interface AutoGenerateDialogProps {
  onAutoGenerate: (data: TournamentData) => void;
  /** True when the form already has player data that would be replaced */
  hasExistingData: boolean;
}

// ============================================================================
// Pure helpers
// ============================================================================

function normalizeCountryCode(code: string): string {
  const normalized = code.toUpperCase();
  return normalized === "UK" ? "GB" : normalized;
}

/**
 * Match each Challonge standings entry to an RK9 roster row.
 * Screen name is tried first, then "first last". Each roster row is used at
 * most once so duplicate handles cannot be claimed twice.
 */
function matchRosterRows(
  entries: StandingEntry[],
  roster: RosterPlayer[]
): ReviewRow[] {
  const used = new Set<number>();

  return entries.map((entry) => {
    const target = normalizePlayerName(applyNameOverride(entry.name));

    let index = roster.findIndex(
      (rp, i) => !used.has(i) && normalizePlayerName(rp.screenName) === target
    );

    if (index === -1) {
      index = roster.findIndex(
        (rp, i) =>
          !used.has(i) &&
          normalizePlayerName(`${rp.firstName}${rp.lastName}`) === target
      );
    }

    if (index !== -1) used.add(index);

    return {
      entry,
      rosterIndex: index === -1 ? null : index,
      autoMatched: index !== -1,
    };
  });
}

/** Sizes the graphic supports that this many ranked players can fill */
function availableSizes(entryCount: number): PlayerCount[] {
  const sizes = SUPPORTED_SIZES.filter((size) => size <= entryCount);
  return sizes.length > 0 ? sizes : [SUPPORTED_SIZES[0]];
}

/** The size the form itself defaults to, used when nothing better is implied */
const FALLBACK_SIZE: PlayerCount = 16;

/**
 * Default to the size that matches the bracket exactly where possible.
 *
 * - A distinct top cut (fewer ranked players than participants) is the
 *   strongest signal - use it.
 * - In pairings mode, use the number of players actually in a live matchup, so
 *   the graphic holds the pairings and nothing else.
 * - Events run as parallel group brackets rank their whole field, which implies
 *   nothing about graphic size, so those fall back to Top 16.
 */
function pickDefaultSize(
  mode: StandingsMode,
  entries: StandingEntry[],
  rankedCount: number,
  fullFieldRanked: boolean
): PlayerCount {
  const sizes = availableSizes(entries.length);

  let target: number = FALLBACK_SIZE;
  if (mode === "final" && rankedCount > 0 && !fullFieldRanked) {
    target = rankedCount;
  } else if (mode === "pairings") {
    const pairingCount = entries.filter((e) => e.source === "pairing").length;
    if (pairingCount > 0) target = pairingCount;
  }

  const exact = sizes.find((size) => size === target);
  if (exact) return exact;

  const fitting = sizes.filter((size) => size <= target);
  return fitting.length > 0 ? fitting[fitting.length - 1] : sizes[0];
}

/**
 * Turn a Challonge tournament name into the graphic's first title line, which
 * is the location. Both naming conventions in use end with the city:
 *   "2027 GO Championships - Brisbane" -> "Brisbane"
 *   "2027_GO_Brisbane"                 -> "Brisbane"
 * The remaining two lines are left for the user to fill in.
 */
function deriveTitleLine(tournamentName: string): string {
  const name = tournamentName.replace(/_/g, " ").trim();

  const dashIndex = name.lastIndexOf(" - ");
  if (dashIndex !== -1) {
    const tail = name.slice(dashIndex + 3).trim();
    if (tail) return tail;
  }

  return name
    .replace(/^\s*\d{4}\s*/, "")
    .replace(/^\s*GO\s+/i, "")
    .replace(/\s*Championships?\s*$/i, "")
    .trim();
}

/**
 * The graphic shows the season year, which is not the calendar year the event
 * is played in - the 2027 season starts in September 2026. The tournament name
 * carries the season ("2027 GO Championships - Brisbane"), so prefer it and
 * only fall back to the start date.
 */
function deriveEventYear(meta: ChallongeTournamentMeta): string {
  const fromName = meta.name.match(/\b(20\d{2})\b/);
  if (fromName) return fromName[1];

  if (meta.startedAt) {
    const year = new Date(meta.startedAt).getFullYear();
    if (!Number.isNaN(year)) return String(year);
  }

  return new Date().getFullYear().toString();
}

/** ISO timestamp -> YYYY-MM-DD, or "" when absent */
function toDateInput(timestamp: string | null): string {
  if (!timestamp) return "";
  const date = new Date(timestamp);
  if (Number.isNaN(date.getTime())) return "";
  return date.toISOString().slice(0, 10);
}

function emptyTeam(): Pokemon[] {
  return Array(6)
    .fill(null)
    .map(() => ({ id: "", isShadow: false }));
}

// ============================================================================
// Component
// ============================================================================

export function AutoGenerateDialog({
  onAutoGenerate,
  hasExistingData,
}: AutoGenerateDialogProps) {
  const [open, setOpen] = React.useState(false);
  const [step, setStep] = React.useState<Step>("input");

  const [challongeUrl, setChallongeUrl] = React.useState("");
  const [rosterUrl, setRosterUrl] = React.useState("");
  const [error, setError] = React.useState<string | null>(null);
  const [isFetching, setIsFetching] = React.useState(false);

  const [mode, setMode] = React.useState<StandingsMode>("final");
  const [rankedCount, setRankedCount] = React.useState(0);
  const [fullFieldRanked, setFullFieldRanked] = React.useState(false);
  const [tournamentMeta, setTournamentMeta] =
    React.useState<ChallongeTournamentMeta | null>(null);
  const [roster, setRoster] = React.useState<RosterPlayer[]>([]);
  const [rows, setRows] = React.useState<ReviewRow[]>([]);

  const [playerCount, setPlayerCount] = React.useState<PlayerCount>(16);
  const [applyPlacements, setApplyPlacements] = React.useState(true);
  const [importStatus, setImportStatus] = React.useState("");

  const sizeOptions = React.useMemo(
    () => availableSizes(rows.length),
    [rows.length]
  );

  const selectedRows = React.useMemo(
    () => rows.slice(0, playerCount),
    [rows, playerCount]
  );

  const unmatchedCount = selectedRows.filter(
    (row) => row.rosterIndex === null
  ).length;

  const approximateCount = selectedRows.filter(
    (row) => row.entry.source === "swiss"
  ).length;

  // Some organizers leave team lists unpublished ("Submitted" on RK9 rather
  // than a View link), so a matched player can still have no team to import
  const noTeamListCount = selectedRows.filter(
    (row) => row.rosterIndex !== null && !roster[row.rosterIndex]?.teamListUrl
  ).length;

  const handleFetch = async () => {
    if (!challongeUrl.trim() || !rosterUrl.trim()) {
      setError("Both a Challonge URL and an RK9 roster URL are required");
      return;
    }

    setIsFetching(true);
    setError(null);

    try {
      const [challongeResponse, rosterResponse] = await Promise.all([
        fetch("/api/challonge-import", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ url: challongeUrl.trim() }),
        }),
        fetch("/api/rk9-roster", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ url: rosterUrl.trim() }),
        }),
      ]);

      const challongeResult = await challongeResponse.json();
      const rosterResult = await rosterResponse.json();

      if (!challongeResult.success) {
        setError(challongeResult.error || "Failed to load the Challonge tournament");
        return;
      }

      if (!rosterResult.success) {
        setError(rosterResult.error || "Failed to load the RK9 roster");
        return;
      }

      const entries: StandingEntry[] = challongeResult.entries;
      const rosterPlayers: RosterPlayer[] = rosterResult.players;

      setMode(challongeResult.mode);
      setRankedCount(challongeResult.rankedCount);
      setFullFieldRanked(challongeResult.fullFieldRanked);
      setTournamentMeta(challongeResult.tournament);
      setRoster(rosterPlayers);
      setRows(matchRosterRows(entries, rosterPlayers));

      const defaultSize = pickDefaultSize(
        challongeResult.mode,
        entries,
        challongeResult.rankedCount,
        challongeResult.fullFieldRanked
      );
      setPlayerCount(defaultSize);
      setApplyPlacements(challongeResult.mode === "final");
      setStep("review");
    } catch {
      setError("Failed to connect to server");
    } finally {
      setIsFetching(false);
    }
  };

  const handleRosterChange = (rowIndex: number, value: string) => {
    setRows((prev) =>
      prev.map((row, i) =>
        i === rowIndex
          ? {
              ...row,
              rosterIndex: value === "__skip__" ? null : Number(value),
              autoMatched: false,
            }
          : row
      )
    );
  };

  const handleImport = async () => {
    if (!tournamentMeta) return;

    setStep("importing");
    setError(null);

    try {
      // Fetch every matched team list in one batched request
      const urlByRow = new Map<number, string>();
      selectedRows.forEach((row, i) => {
        const url =
          row.rosterIndex !== null ? roster[row.rosterIndex]?.teamListUrl : undefined;
        if (url) urlByRow.set(i, url);
      });

      const urls = Array.from(urlByRow.values());
      const teamByUrl = new Map<string, RK9TeamData>();

      if (urls.length > 0) {
        setImportStatus(`Fetching ${urls.length} team lists...`);

        const response = await fetch("/api/rk9-teams", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ urls }),
        });
        const result = await response.json();

        if (!result.success) {
          setError(result.error || "Failed to fetch team lists");
          setStep("review");
          return;
        }

        for (const entry of result.results as Array<{
          url: string;
          data: RK9TeamData | null;
        }>) {
          if (entry.data) teamByUrl.set(entry.url, entry.data);
        }
      }

      // Resolve Pokemon names to species IDs, reusing the single-player path
      const data = createDefaultTournamentData(playerCount, "Usage");

      for (let i = 0; i < selectedRows.length; i++) {
        setImportStatus(`Resolving teams (${i + 1}/${selectedRows.length})...`);

        const row = selectedRows[i];
        const playerId = data.playerOrder[i];
        const rosterPlayer =
          row.rosterIndex !== null ? roster[row.rosterIndex] : undefined;
        const url = urlByRow.get(i);
        const teamData = url ? teamByUrl.get(url) : undefined;

        let name = rosterPlayer?.screenName?.trim() || row.entry.name;
        let team = emptyTeam();

        if (teamData) {
          const converted = await convertRK9ToFormData(teamData);
          team = converted.data.team;
          // convertRK9ToFormData applies the known RK9 display-name mappings
          if (converted.data.name) name = converted.data.name;
        }

        const knownFlags = getFlagsForPlayer(name);
        const flags = knownFlags
          ? knownFlags
          : rosterPlayer?.country
            ? [normalizeCountryCode(rosterPlayer.country)]
            : [""];

        data.players[playerId] = { id: playerId, name, team, flags };
      }

      data.titleLines = [deriveTitleLine(tournamentMeta.name), "", ""];
      data.eventYear = deriveEventYear(tournamentMeta);

      const startDate = toDateInput(tournamentMeta.startedAt);
      const endDate = toDateInput(tournamentMeta.completedAt) || startDate;
      data.eventDateRange = { startDate, endDate };

      if (applyPlacements) {
        data.columnWrappers = buildPlacementColumnWrappers(playerCount);
        data.bracketLabels = {
          winners: { enabled: false, text: "Winners Bracket" },
          losers: { enabled: false, text: "Losers Bracket" },
        };
      }

      onAutoGenerate(data);
      handleClose();
    } catch {
      setError("Failed to build the tournament data");
      setStep("review");
    } finally {
      setImportStatus("");
    }
  };

  const handleClose = () => {
    setOpen(false);
    setStep("input");
    setChallongeUrl("");
    setRosterUrl("");
    setError(null);
    setIsFetching(false);
    setTournamentMeta(null);
    setRoster([]);
    setRows([]);
    setImportStatus("");
  };

  return (
    <Dialog
      open={open}
      onOpenChange={(isOpen) => {
        if (!isOpen) handleClose();
        else setOpen(true);
      }}
    >
      <DialogTrigger asChild>
        <Button type="button" variant="outline" size="sm" className="text-xs">
          <Wand2 className="h-3 w-3 mr-1" />
          Auto-Generate
        </Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-2xl">
        <DialogHeader>
          <DialogTitle>Auto-Generate from RK9 + Challonge</DialogTitle>
          <DialogDescription>
            Builds the whole form from a Challonge bracket and an RK9 roster:
            standings order, player names, flags, and all six Pokemon per player.
          </DialogDescription>
        </DialogHeader>

        {step === "input" && (
          <div className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="challonge-url">Challonge URL</Label>
              <Input
                id="challonge-url"
                type="url"
                value={challongeUrl}
                onChange={(e) => setChallongeUrl(e.target.value)}
                placeholder="https://pokemongochampionshipseries.challonge.com/..."
                disabled={isFetching}
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="roster-url">RK9 Roster URL</Label>
              <Input
                id="roster-url"
                type="url"
                value={rosterUrl}
                onChange={(e) => setRosterUrl(e.target.value)}
                placeholder="https://rk9.gg/roster/..."
                disabled={isFetching}
              />
              <p className="text-xs text-muted-foreground">
                The roster page supplies country flags and each player&apos;s team
                list link.
              </p>
            </div>
          </div>
        )}

        {step === "review" && (
          <div className="space-y-4">
            {/* Summary */}
            <div className="flex flex-wrap items-center gap-3 text-sm">
              <span className="px-2 py-0.5 rounded bg-blue-500/10 text-blue-700 dark:text-blue-400 text-xs">
                {mode === "final" ? "Final standings" : "Day 2 pairings"}
              </span>
              {mode === "final" && (
                <span className="text-xs text-muted-foreground">
                  {fullFieldRanked
                    ? `Whole field ranked (${rankedCount})`
                    : `Top cut of ${rankedCount}`}
                </span>
              )}
              <span className="text-xs text-muted-foreground">
                {rows.length} ranked players
              </span>
            </div>

            {/* Size + options */}
            <div className="flex flex-wrap items-center gap-4">
              <div className="flex items-center gap-2">
                <Label htmlFor="auto-size" className="text-sm">
                  Graphic size
                </Label>
                <Select
                  value={String(playerCount)}
                  onValueChange={(value) =>
                    setPlayerCount(Number(value) as PlayerCount)
                  }
                >
                  <SelectTrigger id="auto-size" className="h-8 w-28">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    {sizeOptions.map((size) => (
                      <SelectItem key={size} value={String(size)}>
                        Top {size}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              <div className="flex items-center gap-2">
                <Checkbox
                  id="auto-placements"
                  checked={applyPlacements}
                  onCheckedChange={(checked) => setApplyPlacements(checked === true)}
                />
                <Label htmlFor="auto-placements" className="text-sm font-normal">
                  Apply placement labels
                </Label>
              </div>
            </div>

            {/* Warnings */}
            {approximateCount > 0 && (
              <div className="flex items-start gap-2 p-3 text-sm bg-amber-500/10 text-amber-700 dark:text-amber-400 rounded-md">
                <AlertTriangle className="h-4 w-4 mt-0.5 shrink-0" />
                <p>
                  {approximateCount} player{approximateCount !== 1 ? "s are" : " is"}{" "}
                  ordered past the top cut. Challonge does not expose its swiss
                  tiebreakers, so those rows use match record and game differential
                  only &mdash; check them against the official standings.
                </p>
              </div>
            )}

            {unmatchedCount > 0 && (
              <div className="flex items-start gap-2 p-3 text-sm bg-destructive/10 text-destructive rounded-md">
                <AlertTriangle className="h-4 w-4 mt-0.5 shrink-0" />
                <p>
                  {unmatchedCount} player{unmatchedCount !== 1 ? "s" : ""} could not
                  be matched to the roster. Pick the right entry below, or leave it
                  skipped to import the name with an empty team.
                </p>
              </div>
            )}

            {noTeamListCount > 0 && (
              <div className="flex items-start gap-2 p-3 text-sm bg-amber-500/10 text-amber-700 dark:text-amber-400 rounded-md">
                <AlertTriangle className="h-4 w-4 mt-0.5 shrink-0" />
                <p>
                  {noTeamListCount} matched player
                  {noTeamListCount !== 1 ? "s have" : " has"} no public team list
                  on RK9 &mdash; the organizer has not published them. Those players
                  import with a name and flag only.
                </p>
              </div>
            )}

            {hasExistingData && (
              <div className="flex items-start gap-2 p-3 text-sm bg-amber-500/10 text-amber-700 dark:text-amber-400 rounded-md">
                <AlertTriangle className="h-4 w-4 mt-0.5 shrink-0" />
                <p>This replaces everything currently in the form.</p>
              </div>
            )}

            {/* Review table */}
            <div className="max-h-72 overflow-y-auto rounded-md border">
              <table className="w-full text-sm">
                <thead className="sticky top-0 bg-muted">
                  <tr className="text-left">
                    <th className="px-2 py-1.5 w-10 font-medium">#</th>
                    <th className="px-2 py-1.5 font-medium">Challonge</th>
                    <th className="px-2 py-1.5 font-medium">RK9 match</th>
                    <th className="px-2 py-1.5 w-16 font-medium">Flag</th>
                  </tr>
                </thead>
                <tbody>
                  {selectedRows.map((row, index) => {
                    const rosterPlayer =
                      row.rosterIndex !== null ? roster[row.rosterIndex] : undefined;

                    return (
                      <tr key={index} className="border-t">
                        <td className="px-2 py-1.5 text-muted-foreground">
                          {index + 1}
                        </td>
                        <td className="px-2 py-1.5">
                          <span className="truncate">{row.entry.name}</span>
                          {row.entry.source === "swiss" && (
                            <span className="ml-1.5 text-xs text-amber-700 dark:text-amber-400">
                              approx
                            </span>
                          )}
                        </td>
                        <td className="px-2 py-1.5">
                          {row.autoMatched ? (
                            <span className="text-muted-foreground">
                              {rosterPlayer?.screenName}
                              {!rosterPlayer?.teamListUrl && (
                                <span className="ml-1.5 text-xs text-amber-700 dark:text-amber-400">
                                  no team list
                                </span>
                              )}
                            </span>
                          ) : (
                            <Select
                              value={
                                row.rosterIndex === null
                                  ? "__skip__"
                                  : String(row.rosterIndex)
                              }
                              onValueChange={(value) =>
                                handleRosterChange(index, value)
                              }
                            >
                              <SelectTrigger className="h-7 text-xs">
                                <SelectValue />
                              </SelectTrigger>
                              <SelectContent className="max-h-64">
                                <SelectItem value="__skip__">
                                  <span className="text-muted-foreground">
                                    Skip (no team)
                                  </span>
                                </SelectItem>
                                {roster.map((rp, rosterIndex) => (
                                  <SelectItem
                                    key={rosterIndex}
                                    value={String(rosterIndex)}
                                  >
                                    {rp.screenName || `${rp.firstName} ${rp.lastName}`}
                                  </SelectItem>
                                ))}
                              </SelectContent>
                            </Select>
                          )}
                        </td>
                        <td className="px-2 py-1.5 text-xs text-muted-foreground">
                          {rosterPlayer?.country
                            ? normalizeCountryCode(rosterPlayer.country)
                            : "-"}
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          </div>
        )}

        {step === "importing" && (
          <div className="flex items-center gap-2 py-6 text-sm text-muted-foreground">
            <Loader2 className="h-4 w-4 animate-spin" />
            {importStatus || "Importing..."}
          </div>
        )}

        {error && (
          <div className="p-3 text-sm bg-destructive/10 text-destructive rounded-md">
            {error}
          </div>
        )}

        <DialogFooter>
          <Button
            type="button"
            variant="outline"
            onClick={handleClose}
            disabled={step === "importing"}
          >
            Cancel
          </Button>

          {step === "input" && (
            <Button
              type="button"
              onClick={handleFetch}
              disabled={!challongeUrl.trim() || !rosterUrl.trim() || isFetching}
            >
              {isFetching ? (
                <>
                  <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                  Fetching...
                </>
              ) : (
                "Fetch"
              )}
            </Button>
          )}

          {step === "review" && (
            <>
              <Button type="button" variant="outline" onClick={() => setStep("input")}>
                Back
              </Button>
              <Button type="button" onClick={handleImport}>
                {hasExistingData ? "Replace form & import" : "Import"}
              </Button>
            </>
          )}
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
